pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
	stage('Checkout') {
	        agent any
            steps {
                checkout scm
            }
        }
        stage('Build') {
            agent { docker 'php' }
            steps {
                echo 'Building'
		        //sh 'composer install'
		        sh 'php --version'
		        sh './vendor/bin/phpunit'
            }
        }
        stage('Test') {
            agent {
                label '!windows'
            }
            steps {
                echo 'Executing SonarQube scan'
                script {
                    scannerHome = tool 'SonarQube Scanner'
                }
                withSonarQubeEnv('SonarQube_Hive') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sqp_95ec0aa97b17a116a718b1ce1f5240e2dc006d9e"
                }
            }
        }
        stage('Deploy') {
            agent any
            steps {
                echo 'Deploying'
            }
        }
    }
}