version: "3"
services:
    db:
      build: ./app/db/
      container_name: hive-db
      restart: always
      volumes:
        - hive-db:/var/lib/mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: "hive"
      ports:
        - "3306:3306"

    app:
        build: ./app/
        container_name: hive
        ports:
          - "8000:80"
        depends_on:
          - db

    jenkins:
        build: ./app/jenkins/
        container_name: jenkins
        restart: on-failure
        privileged: true
        user: root
        volumes:
          - jenkins-data:/var/jenkins_home
          - jenkins-docker-certs:/certs/client:ro
        environment:
          - DOCKER_HOST=tcp://docker:2376
          - DOCKER_CERT_PAT=/certs/client
          - DOCKER_TLS_VERIFY=1
        ports:
          - "8080:8080"

    sonarqube:
      image: sonarqube:latest
      restart: unless-stopped
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      ports:
        - "9000:9000"

volumes:
  hive-db:
  jenkins-data:
  jenkins-docker-certs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: