version: "3.8"

networks:
  docker:
    driver: bridge

volumes:
  hive-db:
  jenkins_home:
  dind-certs-ca:
  dind-certs-client:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

services:
    db:
      build: ./app/db/
      container_name: hive-db
      volumes:
        - hive-db:/var/lib/mysql
      environment:
        MYSQL_DATABASE: "hive"
        MYSQL_ROOT_PASSWORD: password1234
      ports:
        - "3304:3306"

    app:
        build: ./app/
        container_name: hive
        ports:
          - "8000:80"
        depends_on:
          - db

    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - jenkins_home:/var/jenkins_home
      networks:
        - docker

    dind:
      image: docker:19.03.7-dind
      container_name: dind
      restart: unless-stopped
      privileged: true
      environment:
        - DOCKER_TLS_CERTDIR=/certs
      volumes:
        - dind-certs-ca:/certs/ca
        - dind-certs-client:/certs/client
      networks:
        - docker
      expose:
        - 2375

    sonarqube:
      image: sonarqube:latest
      container_name: sonarqube_hive
      restart: always
      networks:
        docker:
          aliases:
            - docker
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      ports:
        - "9000:9000"
